plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.kakituku.keirinracegate'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.kakituku.keirinracegate'
        minSdk 24
        targetSdk 35
        versionCode 62
        versionName '4.8.1'
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
